Make drives shown on FreeBSD 12.x
jrgp/linfo pull request #130
Opened 2023-03-04 16:27 UTC by hbokh

This will fix #127.
"Works on my machine" - FreeBSD 12.4

![Screenshot 2023-03-04 at 17 25 46](https://user-images.githubusercontent.com/519955/222917335-4a4971aa-4490-47a1-992e-e0fb7673a6a7.png)

2023-03-04 16:51 UTC, hbokh commented
Good enough for now.
I can't get the longer names  under "Name" (yet):
- `ada0: <Samsung SSD 840 EVO 120GB EXT0BB6Q>`
- `cd0: <PLDS DVD+-RW DU-8A5LH 6D11>`

2023-03-04 22:47 UTC, jrgp requested changes

2023-03-05 10:05 UTC, hbokh commented on src/Linfo/OS/FreeBSD.php
> +            case $this >= "8.2":
I could give this a try, but I'm not a programmer: I kick things long enough until they work. 

I could also just change the hard coded version of 8.2 into 12.4... 😏

2023-03-05 10:11 UTC, hbokh commented on src/Linfo/OS/FreeBSD.php
> +            case $this >= "8.2":
Not being a programmer, but I'll give this a try.

2023-03-05 20:47 UTC, merged